spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/${schema.name}?createDatabaseIfNotExist=TRUE"
    username: root
    password: admin
  flyway:
    locations: ["classpath:db/migration/mysql/tables", "classpath:db/migration/mysql/data_non_prod"]
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: validate

logging:
  level:
    ROOT: INFO
    com.example.springboot: debug
    org.hibernate:
      SQL: DEBUG
      type: trace
    org.springframework.cache: debug

app:
  outcall:
    jsonplaceholder:
      mock:
        enabled: false
        directory: src/resources
