spring:
  schema:
    name: db
  datasource:
    url: jdbc:mysql://localhost:3306/${schema.name}
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: password
  flyway:
    locations: ["classpath:db/migration/mysql/tables", "classpath:db/migration/mysql/data_non_prod"]
    enabled: true
    #    placeholder: #sqlServer
    #      go: go
    #      datetimeoffset: datetimeoffset
    #      nonclustered: nonclustered
    create-schemas: ${schema.name}
    default-schema: ${schema.name}

logging:
  level:
    ROOT: INFO
    com.example.springboot: debug
    org.hibenate:
      SQL: DEBUG
      type: trace
    org.springframework.cache: debug